spring.application.name=demo
# --- PUERTO DEL SERVIDOR  ---
server.port=8080

# --- CONFIGURACIÓN DE BASE DE DATOS ---
spring.datasource.url=jdbc:mysql://localhost:3306/pms_db
spring.datasource.username=root
spring.datasource.password=
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# --- CONFIGURACIÓN DE JPA / HIBERNATE ---
# Controla si las tablas se crean automáticamente
spring.jpa.hibernate.ddl-auto=update
# Muestra las consultas SQL en consola
spring.jpa.show-sql=true

# Se cambia a MySQLDialect para evitar el Warning de 'deprecated' en Java 22
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# Desactiva el Warning de open-in-view en la consola
spring.jpa.open-in-view=false

# ---

spring.datasource.hikari.minimum-idle=5
spring.datasource.hikari.maximum-pool-size=20
